/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package launchpad;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLDecoder;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Mathew
 */
public class LaunchPadForm extends javax.swing.JFrame {

    DefaultListModel defaultListModel=new DefaultListModel();
    File pathWorkingDirectory = new File(System.getProperty("user.dir"));
    
    /**
     * Creates new form LaunchPadForm
     * @throws java.io.IOException
     */
    public LaunchPadForm() throws IOException, FileNotFoundException, URISyntaxException {
        initComponents();
        //importSessionList();
        getSessionList();
        //updateSessionList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSessions = new javax.swing.JList<>();
        jTextFieldConnectHostname = new javax.swing.JTextField();
        jTextFieldConnectUsername = new javax.swing.JTextField();
        jPasswordFieldConnectPassword = new javax.swing.JPasswordField();
        jButtonHTTPS = new javax.swing.JButton();
        jButtonSSH = new javax.swing.JButton();
        jTextFieldPingHostname = new javax.swing.JTextField();
        jCheckBoxDNS = new javax.swing.JCheckBox();
        jButtonPing = new javax.swing.JButton();
        jButtonTracert = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NSB LaunchPad ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(410, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(410, 500));
        getContentPane().setLayout(null);

        jTextFieldFilter.setText("jTextField1");
        jTextFieldFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFilterKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldFilter);
        jTextFieldFilter.setBounds(0, 0, 190, 20);

        jListSessions.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jListSessions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListSessions);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 20, 190, 470);

        jTextFieldConnectHostname.setText("255.255.255.255");
        jTextFieldConnectHostname.setToolTipText("IP or DNS Hostname");
        jTextFieldConnectHostname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConnectHostnameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldConnectHostname);
        jTextFieldConnectHostname.setBounds(200, 10, 120, 20);

        jTextFieldConnectUsername.setText("mathew.j.bray.civ");
        jTextFieldConnectUsername.setToolTipText("Username");
        getContentPane().add(jTextFieldConnectUsername);
        jTextFieldConnectUsername.setBounds(200, 40, 120, 20);

        jPasswordFieldConnectPassword.setText("jPasswordField1");
        jPasswordFieldConnectPassword.setToolTipText("Password");
        getContentPane().add(jPasswordFieldConnectPassword);
        jPasswordFieldConnectPassword.setBounds(200, 60, 120, 20);

        jButtonHTTPS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonHTTPS.setText("HTTPS");
        jButtonHTTPS.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonHTTPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHTTPSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHTTPS);
        jButtonHTTPS.setBounds(330, 10, 60, 30);

        jButtonSSH.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonSSH.setText("SSH");
        jButtonSSH.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSSHActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSSH);
        jButtonSSH.setBounds(330, 40, 60, 40);

        jTextFieldPingHostname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPingHostname.setText("jTextField4");
        jTextFieldPingHostname.setToolTipText("IP or DNS Hostname");
        getContentPane().add(jTextFieldPingHostname);
        jTextFieldPingHostname.setBounds(200, 100, 120, 21);

        jCheckBoxDNS.setSelected(true);
        jCheckBoxDNS.setText("DNS");
        getContentPane().add(jCheckBoxDNS);
        jCheckBoxDNS.setBounds(330, 100, 50, 20);

        jButtonPing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPing.setText("PING");
        jButtonPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPingActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPing);
        jButtonPing.setBounds(200, 130, 80, 25);

        jButtonTracert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTracert.setText("TRACERT");
        jButtonTracert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTracertActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTracert);
        jButtonTracert.setBounds(290, 130, 100, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launchpad/images/buttons/apps.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 180, 40, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launchpad/images/buttons/apps.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 180, 40, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launchpad/images/buttons/apps.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 180, 40, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launchpad/images/buttons/apps.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 180, 40, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launchpad/images/buttons/apps.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(200, 230, 40, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launchpad/images/buttons/apps.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(250, 230, 40, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launchpad/images/buttons/apps.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(300, 230, 40, 40);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launchpad/images/buttons/apps.png"))); // NOI18N
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(350, 230, 40, 40);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(200, 90, 190, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(200, 170, 190, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSSHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSSHActionPerformed

    private void jButtonPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPingActionPerformed
        // TODO add your handling code here:
        System.out.println("Pressed"); 
        try {  
            // We are running "dir" and "ping" command on cmd 
            Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"ping -t " + jTextFieldPingHostname.getText() + "\""); 
        } 
        catch (IOException e) { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
        } 
    }//GEN-LAST:event_jButtonPingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Pressed"); 
        try {  
            // We are running "dir" and "ping" command on cmd 
            Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"dir && ping localhost\""); 
        } 
        catch (IOException e) { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonHTTPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHTTPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHTTPSActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextFieldConnectHostnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConnectHostnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConnectHostnameActionPerformed

    private void jTextFieldFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilterKeyReleased
        // TODO add your handling code here:
        try {
            searchFilter(jTextFieldFilter.getText());
        } catch (IOException ex) {
            Logger.getLogger(LaunchPadForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(LaunchPadForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldFilterKeyReleased

    private void jButtonTracertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTracertActionPerformed
        // TODO add your handling code here:
        System.out.println("Pressed"); 
        try {  
            // We are running "dir" and "ping" command on cmd 
            Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"tracert " + jTextFieldPingHostname.getText() + "\""); 
        } 
        catch (IOException e) { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
        } 
    }//GEN-LAST:event_jButtonTracertActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaunchPadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaunchPadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaunchPadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaunchPadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new LaunchPadForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(LaunchPadForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(LaunchPadForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

   
     private ArrayList getSessionList() throws FileNotFoundException, IOException, URISyntaxException
    {
        ArrayList arrSessionList=new ArrayList();
        DefaultListModel listModel = new DefaultListModel();
        File pathDesktop = new File(System.getProperty("user.home"), "Desktop");
        //File pathWorkingDirectory = new File(System.getProperty("user.dir"));
        System.out.println("SessionList.csv directory: " + pathDesktop);
        File archivo = new File(pathDesktop + "/SessionList.csv");
        try (FileReader fr = new FileReader(archivo)) {
            BufferedReader buffIn = new BufferedReader(fr);
               
            String line;
            while ((line = buffIn.readLine()) != null) {
                arrSessionList.add(line);
                listModel.addElement(line);
                System.out.println(line);
            }
        jListSessions.setModel(listModel);
        }

        return arrSessionList;
    }
     
    private void searchFilter(String searchTerm) throws IOException, FileNotFoundException, URISyntaxException
    {
        DefaultListModel filteredItems=new DefaultListModel();
        ArrayList stars=getSessionList();

        stars.stream().forEach((star) -> {
            String starName=star.toString().toLowerCase();
            if (starName.contains(searchTerm.toLowerCase())) {
                filteredItems.addElement(star);
            }
        });
        defaultListModel=filteredItems;
        jListSessions.setModel(defaultListModel);

    }
    
        //--- Filter the ListBox
//        try (FileReader fr = new FileReader(arrSessionList)) {
//            BufferedReader buffIn = new BufferedReader(fr);
//            DefaultListModel listModel = new DefaultListModel();
//            String line;
//            while ((line = buffIn.readLine()) != null) {
//                listModel.addElement(line);
//            }
//            jListSessions.setModel(listModel);
//            }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonHTTPS;
    private javax.swing.JButton jButtonPing;
    private javax.swing.JButton jButtonSSH;
    private javax.swing.JButton jButtonTracert;
    private javax.swing.JCheckBox jCheckBoxDNS;
    private javax.swing.JList<String> jListSessions;
    private javax.swing.JPasswordField jPasswordFieldConnectPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldConnectHostname;
    private javax.swing.JTextField jTextFieldConnectUsername;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTextField jTextFieldPingHostname;
    // End of variables declaration//GEN-END:variables


}
